[kijanikiosk]
api-staging ansible_host=REPLACE_API_IP ansible_user=ubuntu
payments-staging ansible_host=REPLACE_PAYMENTS_IP ansible_user=ubuntu
logs-staging ansible_host=REPLACE_LOGS_IP ansible_user=ubuntu

[kijanikiosk:vars]
ansible_ssh_private_key_file=~/.ssh/kijani-admin-key.pem
ansible_python_interpreter=/usr/bin/python3
